"""Copy the plugin's shaders and tables into the demo, by script, never by hand.

    python3 demo/tools/sync_shaders.py          rewrite the generated block of demo/plugin.js
    python3 demo/tools/sync_shaders.py --print  print the block instead

`demo/plugin.js` carries one region between the lines

    //=== BEGIN GENERATED by demo/tools/sync_shaders.py
    //=== END GENERATED

and this script owns it. Everything in it is text lifted out of the C++:

  - the eight GLSL strings of `source/Shaders.cpp` (the version line, the vertex
    body, the `kFilament` library and the six pass bodies), each spliced into a
    JavaScript template literal with its tabs, its comments and its blank lines
    exactly as they are. A template literal cannot hold a raw backtick, a
    backslash or a `${`, so those three are escaped (`kFilament` quotes
    `cycles` in backticks in a comment) and `check_shaders.py` undoes exactly
    those three and refuses any other escape;
  - the numbers the lamp is made of (`source/Lamp.h`: the resistivity table,
    the Shomate coefficients, the design point, the assumed constants, the
    substep rule's constants), the picture's constants (`source/Model.h`), the
    control ranges and option lists (`source/Controls.h`, `Controls.cpp`) and the
    Planck colour table (`source/PlanckTable.h`), each literal copied as the C++
    spells it, less a float's `f` suffix.

What this script does NOT write is the port: `Watts()`, `Make()`, `Stiffness()`,
the substep rule and the clock bookkeeping in plugin.js are a hand translation
of Controls.cpp, Lamp.cpp and Filament::ProcessOpenGL, and only a reader checks
those.

Run it whenever a shader or a table changes in the plugin, then
`python3 demo/tools/check_shaders.py` (tools/verify.sh runs it) to confirm.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
PLUGIN_JS = os.path.join(REPO, "demo", "plugin.js")

BEGIN = "//=== BEGIN GENERATED by demo/tools/sync_shaders.py"
END = "//=== END GENERATED"

# JS constant, C++ symbol in source/Shaders.cpp. Order is the file's order.
SHADERS = [
    ("VERTEX_BODY", "kVertexBody"),
    ("FILAMENT", "kFilament"),
    ("DRIVE_BODY", "kDriveBody"),
    ("THERMAL_BODY", "kThermalBody"),
    ("FILL_BODY", "kFillBody"),
    ("REGRID_BODY", "kRegridBody"),
    ("BLUR_BODY", "kBlurBody"),
    ("OUTPUT_BODY", "kOutputBody"),
]


def read(path):
    with open(os.path.join(REPO, path)) as handle:
        return handle.read()


def cpp_shader(source, symbol):
    match = re.search(r'const char\* const ' + symbol + r' = R"\((.*?)\)";', source, re.S)
    if match is None:
        raise SystemExit(f"{symbol} not found in source/Shaders.cpp")
    return match.group(1)


def cpp_version(source):
    match = re.search(r'const char\* const kVersion = "(.*?)";', source)
    if match is None:
        raise SystemExit("kVersion not found in source/Shaders.cpp")
    return match.group(1)


def escape_template(text):
    return text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def strip_comments(text):
    return re.sub(r"//[^\n]*", "", text)


def number(token):
    """A C++ numeric literal as JavaScript: drop a float's f suffix, nothing else."""
    token = token.strip()
    token = re.sub(r"(?<=[0-9.])f\b", "", token)
    return token


def numbers(body):
    return [number(t) for t in strip_comments(body).replace("\n", " ").split(",") if t.strip()]


def scalars(source, types):
    out = []
    for match in re.finditer(r"constexpr (" + types + r") (k\w+)\s*=\s*([^;{\[]+);", source):
        out.append((match.group(2), number(match.group(3))))
    return out


def arrays(source, types):
    out = []
    for match in re.finditer(r"constexpr (" + types + r") (k\w+)\[[^\]]*\]\s*=\s*\{(.*?)\};", source, re.S):
        out.append((match.group(2), numbers(match.group(3))))
    return out


def names_of(controls_cpp, function):
    match = re.search(function + r"\( int index \)\s*\{\s*static const char\* const names\[ \w+ \] = \{ (.*?) \};", controls_cpp, re.S)
    if match is None:
        raise SystemExit(f"{function}'s names not found in source/Controls.cpp")
    return re.findall(r'"([^"]*)"', match.group(1))


def glass_tints(controls_cpp):
    match = re.search(r"static const float tints\[ kGlassCount \]\[ 3 \] = \{(.*?)\n\t\};", controls_cpp, re.S)
    if match is None:
        raise SystemExit("GlassTint's table not found in source/Controls.cpp")
    rows = re.findall(r"\{([^}]*)\}", strip_comments(match.group(1)))
    return [numbers(r) for r in rows]


def planck(header):
    first = re.search(r"constexpr int kFirstKelvin = (\d+);", header).group(1)
    step = re.search(r"constexpr int kStepKelvin\s*= (\d+);", header).group(1)
    count = re.search(r"constexpr int kCount\s*= (\d+);", header).group(1)
    rows = re.findall(r"^\t\{ ([^}]*) \}, // (\d+) K$", header, re.M)
    if len(rows) != int(count):
        raise SystemExit(f"PlanckTable.h: {len(rows)} rows, kCount says {count}")
    return first, step, count, rows


def obj(pairs, indent="  "):
    return "{\n" + "".join(f"{indent}{k}: {v},\n" for k, v in pairs) + "}"


def js_array(values):
    return "[" + ", ".join(values) + "]"


def block():
    shaders_cpp = read("source/Shaders.cpp")
    lamp_h = read("source/Lamp.h")
    model_h = read("source/Model.h")
    controls_h = read("source/Controls.h")
    controls_cpp = read("source/Controls.cpp")
    planck_h = read("source/PlanckTable.h")

    out = [BEGIN + " from source/ -- do not edit by hand.", ""]
    out.append("// source/Shaders.cpp, verbatim. `assemble` (below the block) is Shaders.cpp's.")
    out.append(f'const K_VERSION = "{cpp_version(shaders_cpp)}";')
    out.append("")
    for name, symbol in SHADERS:
        out.append(f"const {name} = `{escape_template(cpp_shader(shaders_cpp, symbol))}`;")
        out.append("")

    out.append("// source/Lamp.h: the design point, the assumptions, the tables, the substep rule.")
    out.append("const LAMP_H = " + obj(scalars(lamp_h, "double|int")) + ";")
    for name, values in arrays(lamp_h, "double"):
        out.append(f"const LAMP_{name} = {js_array(values)};")
    out.append("")

    out.append("// source/Model.h: the picture's constants, judged by eye in the plugin.")
    out.append("const MODEL_H = " + obj(scalars(model_h, "double|float|int")) + ";")
    for name, values in arrays(model_h, "float|double"):
        out.append(f"const MODEL_{name} = {js_array(values)};")
    out.append("")

    out.append("// source/Controls.h and Controls.cpp: the ranges, the option lists, the glass.")
    out.append("const CONTROLS_H = " + obj(scalars(controls_h, "int")) + ";")
    for js, fn in (("GLASS_NAMES", "GlassName"), ("GELS_NAMES", "GelsName"), ("DIMMER_NAMES", "DimmerName"), ("MAINS_NAMES", "MainsName")):
        out.append(f"const {js} = [" + ", ".join(f"'{n}'" for n in names_of(controls_cpp, fn)) + "];")
    out.append("const GLASS_TINTS = [" + ", ".join(js_array(r) for r in glass_tints(controls_cpp)) + "];")
    out.append("")

    first, step, count, rows = planck(planck_h)
    out.append("// source/PlanckTable.h (itself generated by tools/planck_table.py): rows of")
    out.append("// ( r / Y, g / Y, b / Y, log2( Y / Y(2856 K) ) ), 10 K apart.")
    out.append(f"const PLANCK_FIRST_KELVIN = {first};")
    out.append(f"const PLANCK_STEP_KELVIN = {step};")
    out.append(f"const PLANCK_COUNT = {count};")
    out.append("const PLANCK_TABLE = [")
    for values, kelvin in rows:
        out.append("  " + ", ".join(number(v) for v in values.split(",")) + f", // {kelvin} K")
    out.append("];")
    out.append("")
    out.append(END)
    return "\n".join(out)


def region(js):
    start = js.find(BEGIN)
    stop = js.find(END)
    if start < 0 or stop < 0 or stop < start:
        return None
    return start, stop + len(END)


def main():
    text = block()
    if "--print" in sys.argv:
        print(text)
        return 0
    with open(PLUGIN_JS) as handle:
        js = handle.read()
    where = region(js)
    if where is None:
        raise SystemExit("demo/plugin.js has no generated block (the BEGIN/END GENERATED lines)")
    updated = js[: where[0]] + text + js[where[1]:]
    if updated == js:
        print("demo/plugin.js already matches the plugin's sources")
        return 0
    with open(PLUGIN_JS, "w") as handle:
        handle.write(updated)
    print("demo/plugin.js: generated block rewritten from source/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
