#!/usr/bin/env python3
"""The colour and brightness of a tungsten filament at every temperature.

Writes source/PlanckTable.h: for T from 250 K to 3700 K in 10 K steps, the
light of a black body at T as linear sRGB, split into a chromaticity and a
luminance so the shader can interpolate between rows without the luminance's
orders of magnitude ruining the chromaticity:

    row = ( r / Y, g / Y, b / Y, log2( Y / Y(2856 K) ) )

so that the linear sRGB of a filament at T is chroma * 2^logY, with a filament
at the temperature of CIE Illuminant A (2856 K) at luminance exactly 1.

    python3 tools/planck_table.py            # rewrite source/PlanckTable.h
    python3 tools/planck_table.py --check    # exit 1 if the header differs
    python3 tools/planck_table.py --print    # a few rows, and the locus

--------------------------------------------------------------------- sources

**The colour-matching functions.** The CIE 1931 2-degree standard observer,
x-bar, y-bar, z-bar at 1 nm from 360 to 830 nm, as published in CIE 015:2018
"Colorimetry, 4th Edition" and its dataset CIE 018:2019 (DOI
10.25039/CIE.DS.xvudnb9b), taken from the Colour & Vision Research
Laboratory's database at UCL (http://www.cvrl.org/database/data/cmfs/
ciexyz31_1.csv, fetched 2026-09-25) and committed unedited as
tools/data/ciexyz31_1.csv. Its SHA-256 is checked below, so an edited copy is
refused rather than silently used.

**Planck's law**, with the 2019 SI exact values of h, c and k. Only the shape
over 360-830 nm matters: the luminance is normalised to 2856 K.

**sRGB.** IEC 61966-2-1:1999, the XYZ-to-linear-sRGB matrix to four decimals
as the standard prints it (D65 white). Chromaticities outside the sRGB
gamut -- a black body below about 1900 K is redder than the sRGB red primary
-- come out with a negative component, which is kept: the shader works in
unclamped linear light and only the final encode clamps. The harness inverts
the same matrix to recover xy, so what it measures is the chromaticity and
not a gamut-clipped version of it.

--------------------------------------------------------------------- method

    X = sum B(l, T) x-bar(l) dl  over 360..830 nm at 1 nm (the table's own grid)

and likewise Y and Z; then the matrix; then the split. A filament is not a
black body -- tungsten's emissivity falls slowly with wavelength across the
visible, which makes it very slightly bluer than a black body at the same
temperature (a few tens of kelvin in colour temperature). That is left out,
and said so in AGENTS.md: the table is Planckian, and `fitest --colour` checks
that the plugin's colours sit on the Planckian locus.
"""
import argparse
import hashlib
import math
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
HEADER = ROOT / "source" / "PlanckTable.h"
CMF = ROOT / "tools" / "data" / "ciexyz31_1.csv"
CMF_SHA256 = "ccbe601d7abf2227b46007ab29742f1f6bcb8621a6413283fb5ade7626a662c5"

T_FIRST = 250
T_STEP = 10
T_LAST = 3700
T_REFERENCE = 2856.0  # CIE Illuminant A

# IEC 61966-2-1, XYZ -> linear sRGB.
M = [
    [3.2406, -1.5372, -0.4986],
    [-0.9689, 1.8758, 0.0415],
    [0.0557, -0.2040, 1.0570],
]

H = 6.62607015e-34
C = 2.99792458e8
K = 1.380649e-23


def load_cmf():
    data = CMF.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest != CMF_SHA256:
        raise SystemExit("%s is not the committed CVRL file (sha256 %s)" % (CMF, digest))
    rows = []
    for line in data.decode().splitlines():
        parts = line.strip().split(",")
        if len(parts) != 4:
            continue
        rows.append((int(parts[0]), float(parts[1]), float(parts[2]), float(parts[3])))
    if rows[0][0] != 360 or rows[-1][0] != 830 or len(rows) != 471:
        raise SystemExit("unexpected CMF table shape")
    return rows


def planck(nm, kelvin):
    lam = nm * 1e-9
    return (2.0 * H * C * C / lam ** 5) / math.expm1(H * C / (lam * K * kelvin))


def xyz(kelvin, cmf):
    X = Y = Z = 0.0
    for nm, xb, yb, zb in cmf:
        b = planck(nm, kelvin)
        X += b * xb
        Y += b * yb
        Z += b * zb
    return X, Y, Z


def rgb(X, Y, Z):
    return [M[i][0] * X + M[i][1] * Y + M[i][2] * Z for i in range(3)]


def float_literal(v):
    text = "%.9g" % v
    if "." not in text and "e" not in text and "inf" not in text:
        text += ".0"
    return text + "f"


def rows(cmf):
    Yref = xyz(T_REFERENCE, cmf)[1]
    out = []
    for T in range(T_FIRST, T_LAST + 1, T_STEP):
        X, Y, Z = xyz(float(T), cmf)
        r, g, b = rgb(X, Y, Z)
        out.append((T, r / Y, g / Y, b / Y, math.log2(Y / Yref), X / (X + Y + Z), Y / (X + Y + Z)))
    return out


def render(table):
    n = len(table)
    lines = [
        "#pragma once",
        "",
        "// GENERATED by tools/planck_table.py -- do not edit. Run the script.",
        "//",
        "// A black body at T as linear sRGB (IEC 61966-2-1), from the CIE 1931 2-degree",
        "// colour-matching functions at 1 nm (CVRL's copy of CIE 018:2019). Each row is",
        "// ( r / Y, g / Y, b / Y, log2( Y / Y(2856 K) ) ): chromaticity and luminance",
        "// apart, so the shader can interpolate each linearly. Sources and method are",
        "// in the script.",
        "",
        "namespace filament::planck",
        "{",
        "",
        "constexpr int kFirstKelvin = %d;" % T_FIRST,
        "constexpr int kStepKelvin  = %d;" % T_STEP,
        "constexpr int kCount       = %d;" % n,
        "",
        "constexpr float kTable[ kCount ][ 4 ] = {",
    ]
    for T, cr, cg, cb, ly, _, _ in table:
        lines.append("\t{ %s, %s, %s, %s }, // %d K" % (float_literal(cr), float_literal(cg), float_literal(cb), float_literal(ly), T))
    lines += ["};", "", "} // namespace filament::planck", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="compare with the committed header, do not write")
    ap.add_argument("--print", action="store_true", help="print some rows and the locus")
    args = ap.parse_args()

    cmf = load_cmf()
    table = rows(cmf)
    text = render(table)
    if args.print:
        for T, cr, cg, cb, ly, x, y in table:
            if T % 250 == 0 or T == 2850:
                print("%5d K  x=%.5f y=%.5f  rgb/Y=(%.4f %.4f %.4f)  log2Y=%.4f" % (T, x, y, cr, cg, cb, ly))
    if args.check:
        if not HEADER.exists() or HEADER.read_text() != text:
            print("%s does not match what the script computes -- run tools/planck_table.py" % HEADER.relative_to(ROOT))
            return 1
        print("%s recomputes from the CIE 1931 CMFs (sha256 checked), %d rows" % (HEADER.relative_to(ROOT), len(table)))
        return 0
    if not args.print:
        HEADER.write_text(text)
        print("wrote %s" % HEADER.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
